// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../AssemblyInfo.fs"
      "../CommandLine.fsi"
      "../CommandLine.fs"
      "../Common.fsi"
      "../Common.fs"
      "../ErrorPrint.fs"
      "../Error.fs"
      "../CommonAst.fsi"
      "../CommonAst.fs"
      "../PrettyPrint.fsi"
      "../PrettyPrint.fs"
      "../Reduce.fsi"
      "../Reduce.fs"
